name: deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.12
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            image-name: promtail
            image-tag: latest
